ldd-check/ldd-check
This appears to have been the intent.
=> ldd-check: Preserve LD_LIBRARY_PATH when checking python libs

melange.yaml, syspeek-tool/Makefile, syspeek-tool/README.md, syspeek-tool/syspeek
The syspeek tool statically analyses an ELF binary by disassembling and reporting a syscall profile.
The syscall profile can then be compared to a one dynamically generated when running functional tests for the same application executable.
The only application type supported are ones compiled. Script and application that use interpreted languages are not supported by this method.
It needs the syscall table file (`/usr/include/asm/unistd_64.h` by default) and objdump compiled for the same architecture of the target executable.
x86_64 and x86_32 are supported.
For instance:
```shell
$ syspeek myapp
openat
read
gettid
getpid
gettid
tgkill
getpid
kill
getpid
tgkill
setitimer
timer_create
timer_settime
timer_delete
mincore
clock_gettime
rt_sigprocmask
rt_sigaction
mmap
munmap
madvise
futex …
```
=> feat: add syspeek tool to statically generate a syscall profile

ldd-check/ldd-check
ldd-check's exit code would be zero if the number of failures was evenly divisible by 256. Don't `exit $fails`, just `exit 1`.
exit codes are 8 bit. so `exit 256` is the same as `exit 0`.
```
$ sh -c 'exit 256'
$ echo "rc=$?"
0
```
=> Fix false-negative in exit value of ldd-check.

header-check/Makefile, header-check/README.md, header-check/header-check, pipelines/test/tw/header-check.yaml
Here we add a new test -- header-check.  The goal of this script is to test .h and .hpp files, as they are installed.  It will determine whether or not the header files are usable in an autoconf context.  It will succeed, if autoconf is happy with the header as included.  It will fail for a variety of reasons, including bad syntax or use in the header, and possibly other missing, related dependencies (e.g. when a header #includes some other header, which isn't installed as a dependency).
=> Header check

header-check/header-check, pipelines/test/tw/header-check.yaml
Cleaner PR, supporting passthrough input for ./configure options.  Needed for some header tests, such as libb64-1.2
=> Add --configure-opts to pass through compiler flags, etc.

gem-check/Makefile, gem-check/README.md, gem-check/gem-check, header-check/header-check, melange.yaml, pipelines/test/tw/gem-check.yaml
Here's another test check that will check ruby gem installs.
I've run it (manually), and have successful runs from:
1. ruby3.2-json-jwt
2. ruby3.2-jwt
3. ruby3.2-mail
4. ruby3.2-method_source
5. ruby3.2-mini_mime
6. ruby3.2-minitar
7. ruby3.2-multi_json
8. ruby3.2-multi_xml
9. ruby3.2-net-http-persistent
10. ruby3.2-net-protocol
11. ruby3.2-numerizer
12. ruby3.2-openssl_pkcs8_pure
13. ruby3.2-polyglot
14. ruby3.2-protocol-hpack
15. ruby3.2-public_suffix
16. ruby3.2-quantile
17. ruby3.2-rack-oauth2
18. ruby3.2-redis-namespace
19. ruby3.2-redis
20. ruby3.2-rexml
21. ruby3.2-ruby2_keywords
22. ruby3.2-serverengine
23. ruby3.2-sigdump
24. ruby3.2-snaky_hash
25. ruby3.2-swd
26. ruby3.2-thread_safe
27. ruby3.2-timeout
28. ruby3.2-tzinfo-data
29. ruby3.2-tzinfo
30. ruby3.2-validate_email
31. …
=> add a test that checks a ruby gem installation

melange.yaml, tools/release-to-wolfi
getopts is shell builtin.
getopt is way nicer and supports long options.
getopt on mac is some random thing that doesn't behave in a sensical way.
Per Josh:
$ ./tools/release-to-wolfi v0.0.8 ~/dev/gh/wolfi/os
Usage: release-to-wolfi tag wolfi-os/
Release 'tag' to wolfi, where 'wolfi-os' is a wolfi-dev/os
git checkout.
got 8 args expected 2
Thanks mac.
=> tools/release-to-wolfi - replace getopt with getopts (plural/builtin)

melange.yaml, tools/release-to-wolfi
*   Fix release-to-wolfi for version.
the version wasn't getting quoted, which made it randomly
different than the wolfi-preferred way.
Also, take TWGIT from the environment to facilitate easier
testing like
$ git tag v0.13.0
$ TWGIT=$PWD ./tools/release-to-wolfi v0.13.0 ~/src/wolfi-os
*Fixup indentation in melange.yaml
=> Fixup release script again.

.github/workflows/presubmit.yaml, Makefile
this is just a presubmit check to **test** whether melange can build/test, so we just leverage the `docker` runner instead of bwrap since docker is presintalled on GHA hosted runners and the bwrap install takes a minute.
this doesn't publish the apk anywhere
=> use the docker runner for build/test

tw/pkg/commands/helm/inventory.go, tw/pkg/commands/helm/inventory_test.go
- adds logic to ensure proper handling when a `--repo` isn't passed.
- ensures that both a packaged chart and a local chart can be inventoried
- adds a new `local` field to replace `digest` when attempting to inventory a local chart
=> ensure local charts are properly referenced

tw/pkg/commands/helm/helm_test.go, tw/pkg/commands/helm/inventory.go, tw/pkg/commands/helm/inventory_test.go, tw/pkg/commands/helm/testdata/helm-inventory/local-chart.txtar, tw/pkg/commands/helm/testdata/helm-inventory/oci-repo.txtar, tw/pkg/commands/helm/testdata/helm-inventory/standard-repo.txtar
there's waaaaay too many ways to specify a chart repository. its madness.
this PR adds yet another format, the `helm install <name> <oci://>` one.
it also adds the framework for running some lightweight integration tests for the install variations we want to support.
=> ensure oci repo works, and add some lightweight integration tests

go.work.sum, tw/main.go
`helm-inventory` is failing without printing any errors at the moment:
```bash
bash-5.2# helm-inventory --path /mnt/imagetest/artifacts/helm_values/inventory.json --values /tmp/tmp.rlEQjg -- helm install redis oci://registry-1.docker.io/bitnamicharts/redis --debug --namespace default --create-namespace --version 20.9.0 --values /tmp/tmp.PuzhFr --values /tmp/tmp.rlEQjg --wait
2025/04/24 15:52:46 INFO running whelm helm_args="[helm install redis oci://registry-1.docker.io/bitnamicharts/redis --debug --namespace default --create-namespace --version 20.9.0 --values /tmp/tmp.PuzhFr --values /tmp/tmp.rlEQjg --wait]"
2025/04/24 15:52:46 INFO running helm command subcommand="helm install redis oci://registry-1.docker.io/bitnamicharts/redis --debug --namespace default --create-namespace --version …
```
=> fix: print tw command execution errors

tw/pkg/commands/dgrep/dgrep.go, tw/pkg/commands/kgrep/kgrep.go
After the recent change, I am encountering this error where 
These pass: 
```
bash-5.2# tw kgrep -n kube-system deployment/kube-metrics-adapter -e "prometheus"
...
2025/06/20 08:22:19 INFO kgrep succeeded resource="[deployment kube-metrics-adapter]" namespace=kube-system attempt=1 timeout=5s
```
```
bash-5.2# tw kgrep -n kube-system deployment/kube-metrics-adapter -e "Collected new external metric"
...
2025/06/20 08:23:08 INFO kgrep succeeded resource="[deployment kube-metrics-adapter]" namespace=kube-system attempt=1 timeout=5s
```
This fails:
```
bash-5.2# tw kgrep -n kube-system deployment/kube-metrics-adapter -e "Collected new external metric" -e "prometheus"
...
2025/06/20 08:24:08 ERROR [1/1] failed to run kgrep: no match found for pattern(s): [prometheus] resource="[deployment …
```
=> fix: check all expressions before moving to next line

symlink-check/main.go, symlink-check/main_test.go
refactor targetEscapesTree to use (target, link) signature
ref:
https://www.gnu.org/software/coreutils/manual/html_node/ln-invocation.html#ln-invocation
I got confused reading it and thought that keeping the signature closer
to ln behavior will make it more readable.
the behavior now is similar to following:
ln -s <target> <link>
=> symlink-check tweaks

melange.yaml
The `syspeek` tool doesn't need `apk-tools` and `busybox`, so we remove those runtime dependencies.
Also, the test wasn't actually testing anytihng from a functional perspective, so we add a test.
=> fix(melange.yaml/syspeek): remove unneded runtime deps and add test

.github/workflows/presubmit.yaml
See https://github.com/chainguard-dev/actions/tree/main/apt-faster for more info.
The 'setup melange' does installation of apt packages. This will make that go faster.
=> Workflows - run chainguard/apt-faster action.

tw/pkg/commands/shu/retry.go, tw/pkg/commands/shu/retry_test.go
Here I add a flag to run the provided command(s) inside a Bash shell.
The flag is false by default so existing behaviour is maintained.
=> shu retry: Add --in-shell flag

.github/workflows/c-i.yaml, Makefile, melange.yaml
*  Add test-melange to c-i
*  Makefile: separate test-melange from test-subdir
Also here, we now get tab completion for test-<subdir>.
*  build - make local dev version of 999 so these packages are selected.
test in c-i was choosing to install the wolfi packages over the local
packages that it built because the local ones were versioned 0.0.0.
Make local build versions newer than wolfi versions.
*  Rename presubmit to c-i and run as post-submit also.
We were not doing anything on post-submit, lets just do
the same thing as pre-submit.
=> Rename presubmit to c-i and run as post-submit also.

.github/actions/shellcheck/action.yaml, .github/workflows/c-i.yaml, Makefile, pipelines/test/tw/header-check.yaml
This adds some new targets to Makefile:
1. yam -  just have `yam` make your local directory happy.
2. yam-check - see if yam would make changes - exit 1 if it would.
3. lint - run the "lint" things (currently shellcheck and yam)
And now we run 'lint' target from c-i rather than just 'shellcheck'.
There is one less than perfect thing here in when we change the version of tools/bin/yam , the local version will just remain out of date.  Thats not a problem for c-i, but a local dev could be running with an out of date version.
=> Make sure yaml files are formatted with yam

pipelines/test/tw/verify-service.yaml
pr #188 made this use subpkg.name, it should have used context.name. subpkg.name is not valid for use in the main package.
=> verify-service - use context.name, not subpkg.name
